#!/bin/sh

[ "$ACTION" = add ] || exit 0

case "$DEVNAME" in
    input/event*) ;;
    *) exit 0 ;;
esac

sysdev=/sys$DEVPATH
name=
[ -r "$sysdev/device/name" ] && read -r name < "$sysdev/device/name"
dev=
[ -r "$sysdev/dev" ] && read -r dev < "$sysdev/dev"

write_udev_data() {
    type=$1

    [ -n "$dev" ] || return 0
    mkdir -p /run/udev/data

    {
        printf 'I:%s\n' "$(date +%s%6N)"
        printf 'E:ID_INPUT=1\n'
        case "$type" in
            keyboard)
                printf 'E:ID_INPUT_KEY=1\n'
                printf 'E:ID_INPUT_KEYBOARD=1\n'
                ;;
            mouse)
                printf 'E:ID_INPUT_MOUSE=1\n'
                ;;
        esac
        printf 'E:LIBINPUT_DEVICE_GROUP=mdevd:%s\n' "$name"
        printf 'V:1\n'
    } > "/run/udev/data/c${dev%:*}:${dev#*:}"
}

case "$name" in
    *[Kk][Ee][Yy][Bb][Oo][Aa][Rr][Dd]*)
        write_udev_data keyboard
        #[ -e /dev/input/xkbd ] || [ -L /dev/input/xkbd ] || ln -s "/dev/$DEVNAME" /dev/input/xkbd
        ;;
    *[Mm][Oo][Uu][Ss][Ee]*)
        write_udev_data mouse
        #[ -e /dev/input/xmouse ] || [ -L /dev/input/xmouse ] || ln -s "/dev/$DEVNAME" /dev/input/xmouse
        ;;
esac
