-$MODALIAS=.* 0:0 660 @test "$ACTION" != add || /usr/bin/modprobe -bq "$MODALIAS" 2>/dev/null || :
-$PCI_ID=10DE:.* 0:0 660 @test "$ACTION" = add -o "$ACTION" = bind && test "$DRIVER" = nvidia && /usr/bin/expr "$PCI_CLASS" : 03 >/dev/null && /usr/bin/nvidia-modprobe && /usr/bin/nvidia-modprobe -c0 -u || :

null      0:0   666
zero      0:0   666
random    0:0   666
urandom   0:0   666
tty       0:tty 666
ptmx      0:tty 666
console   0:tty 600
tty[0-9]* 0:tty 600

$SUBSYSTEM=rtc 0:clock 660
$SUBSYSTEM=input 0:input 660
dri/renderD.* 0:render 666
$SUBSYSTEM=drm 0:video 660
-.*/controlC[0-9]* 0:audio 660 @/bin/sh -c 'n=${MDEV##*/controlC}; /usr/bin/alsactl restore "$n"'
$SUBSYSTEM=sound 0:audio 660
$SUBSYSTEM=block 0:disk 660
loop-control 0:disk 660
(.*/)?tun 0:0 666
fuse 0:0 666
kvm 0:kvm 666
vfio 0:0 666 =vfio/
vsock 0:0 666
vhost-vsock 0:kvm 666
vhost-net 0:kvm 666
udmabuf 0:kvm 660
