#
# Example configuration file.
#
# See unbound.conf(5) man page, version 1.24.2.
#
# this is a comment.

server:
	interface: 127.0.0.1
	access-control: 127.0.0.0/8 allow
	do-not-query-localhost: no

forward-zone:
	name: "."
	forward-addr: 9.9.9.9
	forward-addr: 1.1.1.1
